# Generated with zope.meta (https://zopemeta.readthedocs.io/) from:
# https://github.com/zopefoundation/meta/tree/master/src/zope/meta/pure-python
[build-system]
requires = [
    "setuptools >= 78.1.1,< 81",
    "wheel",
]
build-backend = "setuptools.build_meta"


[project]
name = "grokcore.site"
version = "5.1.dev0"
description = "Grok-like configuration for Zope local site and utilities"
license = "ZPL-2.1"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Zope :: 3",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Programming Language :: Python",
]
dynamic = ["readme"]
requires-python = ">=3.10"
authors = [
    {name = "Grok Team",email = "zope-dev@zope.dev"},
]
maintainers = [
    {name = "Plone Foundation and contributors",email = "zope-dev@zope.dev"},
]
dependencies = [
    "grokcore.component >= 2.1",
    "martian >= 0.13",
    "persistent",
    "zope.annotation",
    "zope.component",
    "zope.container",
    "zope.event",
    "zope.interface",
    "zope.lifecycleevent",
    "zope.schema",
    "zope.site >= 4.4",
]

[project.optional-dependencies]
test = [
    "zope.app.appsetup",
    "zope.component",
    "zope.configuration",
    "zope.testing",
    "grokcore.content",
]

[project.urls]
Source = "https://github.com/zopefoundation/grokcore.site"
Issues = "https://github.com/zopefoundation/grokcore.site/issues"
Changelog = "https://raw.githubusercontent.com/zopefoundation/grokcore.site/master/CHANGES.rst"

[tool.coverage.run]
branch = true
source = ["grokcore.site"]

[tool.coverage.report]
fail_under = 95
precision = 2
ignore_errors = true
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "pragma: nocover",
    "except ImportError:",
    "raise NotImplementedError",
    "if __name__ == '__main__':",
    "self.fail",
    "raise AssertionError",
    "raise unittest.Skip",
]

[tool.coverage.html]
directory = "parts/htmlcov"

[tool.setuptools.dynamic]
readme = {file = ["README.rst", "CHANGES.rst"]}

